### ISSUE TITLE
Offline installation and use request

### ISSUE THREAD

**Issue by F5Rob** [f5devcentral/f5-journeys-lab-ucs-modifier#1]
Please include deployment instructions and usage for installation on systems that do not have access to the commercial internet. i.e. closed network systems with air gap file transfer capabilities.

**Comment by mnaumiuk** [comment]
Great idea F5Rob, thanks for raising that, we will do it.

**Comment by mnaumiuk** [comment]
Filled internal SOLUTIONS-6783

**Comment by mnaumiuk** [comment]
resolved with version 1.0.1
