### ISSUE TITLE
BUG: Exception: Error reading SSH protocol banner

### ISSUE THREAD

**Issue by artgmolina** [f5devcentral/f5-journeys-lab-ucs-modifier#4]
It happened for a UCS I tried to use.

RROR:	Exception: Error reading SSH protocol banner
ERROR:	Traceback (most recent call last):
ERROR:	  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2211, in _check_banner
ERROR:	    buf = self.packetizer.readline(timeout)
ERROR:	  File "/usr/local/lib/python3.9/site-packages/paramiko/packet.py", line 380, in readline
ERROR:	    buf += self._read_timeout(timeout)
ERROR:	  File "/usr/local/lib/python3.9/site-packages/paramiko/packet.py", line 609, in _read_timeout
ERROR:	    raise EOFError()
ERROR:	EOFError
ERROR:
ERROR:	During handling of the above exception, another exception occurred:
ERROR:
ERROR:	Traceback (most recent call last):
ERROR:	  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2039, in run
ERROR:	    self._check_banner()
ERROR:	  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2215, in _check_banner
ERROR:	    raise SSHException(
ERROR:	paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERROR:
INFO:	Key swap needed with 10.1.1.114, attempting
ERROR:	Exception: Error reading SSH protocol banner
ERROR:	Traceback (most recent call last):
ERROR:	  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2211, in _check_banner
ERROR:	    buf = self.packetizer.readline(timeout)
ERROR:	  File "/usr/local/lib/python3.9/site-packages/paramiko/packet.py", line 380, in readline
ERROR:	    buf += self._read_timeout(timeout)
ERROR:	  File "/usr/local/lib/python3.9/site-packages/paramiko/packet.py", line 609, in _read_timeout
ERROR:	    raise EOFError()
ERROR:	EOFError
ERROR:
ERROR:	During handling of the above exception, another exception occurred:
ERROR:
ERROR:	Traceback (most recent call last):
ERROR:	  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2039, in run
ERROR:	    self._check_banner()
ERROR:	  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2215, in _check_banner
ERROR:	    raise SSHException(
ERROR:	paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERROR:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/local/lib/python3.9/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/usr/local/lib/python3.9/site-packages/paramiko/packet.py", line 609, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ucs-modifier", line 33, in <module>
    sys.exit(load_entry_point('ucs-modifier', 'console_scripts', 'ucs-modifier')())
  File "/modifier/ucs_modifier/calypso_ucs_modifier.py", line 59, in main
    keyswap(address, "root", args.password)
  File "/modifier/ucs_modifier/core/keyswap.py", line 218, in keyswap
    transport = get_transport_password_auth(hostname, username, password, port)
  File "/modifier/ucs_modifier/core/keyswap.py", line 180, in get_transport_password_auth
    transport.start_client()
  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 660, in start_client
    raise e
  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2215, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

**Comment by artgmolina** [comment]
DEBUG:	starting thread (client mode): 0x846fab20
DEBUG:	Local version/idstring: SSH-2.0-paramiko_2.8.1
ERROR:	Exception: Error reading SSH protocol banner
ERROR:	Traceback (most recent call last):
ERROR:	  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2211, in _check_banner
ERROR:	    buf = self.packetizer.readline(timeout)
ERROR:	  File "/usr/local/lib/python3.9/site-packages/paramiko/packet.py", line 380, in readline
ERROR:	    buf += self._read_timeout(timeout)
ERROR:	  File "/usr/local/lib/python3.9/site-packages/paramiko/packet.py", line 609, in _read_timeout
ERROR:	    raise EOFError()
ERROR:	EOFError
ERROR:
ERROR:	During handling of the above exception, another exception occurred:
ERROR:
ERROR:	Traceback (most recent call last):
ERROR:	  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2039, in run
ERROR:	    self._check_banner()
ERROR:	  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2215, in _check_banner
ERROR:	    raise SSHException(
ERROR:	paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERROR:
INFO:	Key swap needed with 10.154.82.114, attempting
DEBUG:	Loading SSH key /root/.ssh/id_rsa
DEBUG:	Host key for 10.1.1.114 not found in known_hosts
DEBUG:	starting thread (client mode): 0x84700100
DEBUG:	Local version/idstring: SSH-2.0-paramiko_2.8.1
ERROR:	Exception: Error reading SSH protocol banner
ERROR:	Traceback (most recent call last):
ERROR:	  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2211, in _check_banner
ERROR:	    buf = self.packetizer.readline(timeout)
ERROR:	  File "/usr/local/lib/python3.9/site-packages/paramiko/packet.py", line 380, in readline
ERROR:	    buf += self._read_timeout(timeout)
ERROR:	  File "/usr/local/lib/python3.9/site-packages/paramiko/packet.py", line 609, in _read_timeout
ERROR:	    raise EOFError()
ERROR:	EOFError
ERROR:
ERROR:	During handling of the above exception, another exception occurred:
ERROR:
ERROR:	Traceback (most recent call last):
ERROR:	  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2039, in run
ERROR:	    self._check_banner()
ERROR:	  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2215, in _check_banner
ERROR:	    raise SSHException(
ERROR:	paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERROR:

**Comment by mnaumiuk** [comment]
The target IP address (-m MGMT_IP) needs to be a working BIG-IP instance where you can log in with the root user and password (-p PASSWORD). The tool (f5-journeys-lab-ucs-modifier) connects to this target unit and copies some basic configuration (mgmt IP, route, root&admin passwords...) to replace in UCS.
