### ISSUE TITLE
paramiko.sftp.SFTPError: Garbage packet received

### ISSUE THREAD

**Issue by dstogsdill** [f5devcentral/f5-journeys-lab-ucs-modifier#7]
**Describe the bug**
When running `ucs-modifier` i get the following output with error message at the bottom:

INFO:	Connected (version 2.0, client OpenSSH_7.4)
INFO:	Key swap needed with 10.x.x.x, attempting
INFO:	Connected (version 2.0, client OpenSSH_7.4)
INFO:	Authentication (keyboard-interactive) successful!
INFO:	[chan 0] Opened sftp connection (server version 3)
Traceback (most recent call last):
  File "/usr/local/bin/ucs-modifier", line 33, in <module>
    sys.exit(load_entry_point('ucs-modifier', 'console_scripts', 'ucs-modifier')())
  File "/modifier/ucs_modifier/calypso_ucs_modifier.py", line 90, in main
    keyswap(address, "root", args.password)
  File "/modifier/ucs_modifier/core/keyswap.py", line 225, in keyswap
    remote_file = sftp.open(filename, "a")
  File "/usr/local/lib/python3.9/site-packages/paramiko/sftp_client.py", line 372, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/usr/local/lib/python3.9/site-packages/paramiko/sftp_client.py", line 822, in _request
    return self._read_response(num)
  File "/usr/local/lib/python3.9/site-packages/paramiko/sftp_client.py", line 852, in _read_response
    t, data = self._read_packet()
  File "/usr/local/lib/python3.9/site-packages/paramiko/sftp.py", line 205, in _read_packet
    raise SFTPError("Garbage packet received")
paramiko.sftp.SFTPError: Garbage packet received

**To Reproduce**
1. Deploy vCMP guest on a viprion chassis
2. Guest is running version 15.1.10.2
3. Run docker - `docker run --platform linux/amd64 -v /Users/donald.stogsdill/Downloads/f5_tf_cms:/UCS -it f5devcentral/f5-journeyslab-ucsmodifier:v1.0.3`
4. Run ucs-modifer - `ucs-modifier -u /UCS/<BACKUP_FILE>.ucs -m <IP> -p <PASSWORD>`

**Expected behavior**
I expect not to receive this error :)
Not sure how to work around this error.  I can SSH to the bigip using the root account & password passed to the utility. 

**Screenshots**
![image](https://github.com/f5devcentral/f5-journeys-lab-ucs-modifier/assets/1187042/5ca5c4a7-51d4-47a2-acc1-1ae1245eb5d1)

**Desktop (please complete the following information):**
 - OS: MacOS 14.0

**Additional context**

**Comment by mnaumiuk** [comment]
fixed in the newest version [1.0.4](https://github.com/f5devcentral/f5-journeys-lab-ucs-modifier/releases/tag/1.0.4)
